### ISSUE TITLE
Allow server setting of server properties: Immutable and 'Is Container'

### ISSUE THREAD

**Issue by mtho11** [hawkular/hawkinit#19]
It would be nice to be able to set server properties of 'Is Container' and 'Immutable' for testing purposes (to simulate inside openshift).

Low priority.

**Comment by jkremser** [comment]
Mike, I wouldn't complicate the hawkinit with this. You can change it by curl:

```bash
curl -ivX PUT -u jdoe:password -d '{ "value":{"Immutable": "false", "In Container": "false", "Bound Address": "0.0.0.0"}}' 'http://localhost:8080/hawkular/inventory/deprecated/feeds/${feedId}/resources/Local~~/data' -H "Content-Type: application/json" -H "Hawkular-Tenant: hawkular"
```

But, with the next agent sync, it'll be overwritten.

**Comment by jkremser** [comment]
reopening, because the curl above doesn't solve anything. Agent won't perform the operation, because it reads the immutable flag from the system property, not from the inventory.

**Comment by josejulio** [comment]
We could modify the configuration file before booting the hawkular image. I [did](https://github.com/hawkular/hawkular-client-ruby/blob/master/.travis/start_hawkular_services.sh#L21-L29) that on the hawkular-client-ruby. 
I'll try to send a PR to hawkinit because i will need it.

**Comment by jkremser** [comment]
done in https://github.com/hawkular/hawkinit/pull/31
