### ISSUE TITLE
Better approach for the default options

### ISSUE THREAD

**Issue by jkremser** [hawkular/hawkinit#26]
Currently it's done in naive way by using a lot of if-thens in here https://github.com/hawkular/hawkinit/blob/master/lib/engine.js#L205

There must be some better way by merging the 2 objects (the original 1 with the defaults if missing) perhaps some function in lodash can do that.

**Comment by josejulio** [comment]
would `Object.assign(defaults, answers);` work?

**Comment by jkremser** [comment]
right, or this guy https://lodash.com/docs/4.17.4#merge
