### ISSUE TITLE
Refactoring for the docker-compose yamls

### ISSUE THREAD

**Issue by jkremser** [hawkular/hawkinit#27]
Currently there is a lot of duplication in those yamls, 

https://github.com/hawkular/hawkinit/blob/master/lib/configs/standalone/hawkfly-new.mustache
https://github.com/hawkular/hawkinit/blob/master/lib/configs/standalone/hawkfly-old.mustache

by creating them more dynamically we could fix it.

**Comment by josejulio** [comment]
I could work on this If you aren't already working on this.
