### ISSUE TITLE
Using 'latest' images (e.g. hawkfly) could mean using old ones

### ISSUE THREAD

**Issue by josejulio** [hawkular/hawkinit#30]
We need to manually issue docker-compose pull to update the images if we want to use the actual latest images.

**Comment by jkremser** [comment]
If I add it like this `docker-compose pull && docker-compose up` it slows down the start process by checking everything, so that I'll add the `docker-compose pull` only if explicitly said so in the full mode (+ the default for the full mode will be yes)
