### ISSUE TITLE
no install instruction or docs

### ISSUE THREAD

**Issue by himdel** [hawkular/hawkinit#5]
The video is not very optimal by itself (not searchable and not visible on the npm site)..

Install instructions for debian are `apt install docker.io docker-compose` apparently.

Also should probably mention that it depends on docker >= 1.12 :)

And the docs should at least mention what it does and how.

**Comment by himdel** [comment]
Also, once it finally suceeds .. what then? I have no idea how to access that..

**Comment by jkremser** [comment]
thx for feedback,
it's fixed in readme.
