### ISSUE TITLE
No Cassandra version 3.0.9

### ISSUE THREAD

**Issue by mtho11** [hawkular/hawkinit#8]
I don't see Cassandra 3.0.9 in the list?
And since C* 3.0.9 is the Hawkular standard version perhaps it should be the default.

**Comment by jkremser** [comment]
I've added it to the list. Better solution would be to get the tags dynamically from https://hub.docker.com/r/library/cassandra/tags/ for each docker image, but their api requires the client to be authorized + all those rate limiters, so for now it's just hard coded in the app
